<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Culinary.LegacyImporter-a2657940-8490-472c-b865-9eecbaf71f31</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexora.Infrastructure\Nexora.Infrastructure.csproj" />
    <ProjectReference Include="..\Nexora.Domain\Nexora.Domain.csproj" />
    <ProjectReference Include="..\Nexora.Application\Nexora.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Importers/" />
  </ItemGroup>
</Project>
