// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexora.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexora.Infrastructure.Migrations.CulinaryDb
{
    [DbContext(typeof(CulinaryDbContext))]
    [Migration("20260603223608_CreateCulinaryRecipeRatings")]
    partial class CreateCulinaryRecipeRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("core_companies_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FeaturedImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("featured_image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ParentId");

                    b.HasIndex("CompanyId", "DisplayOrder");

                    b.HasIndex("CompanyId", "ParentId");

                    b.HasIndex("CompanyId", "Slug")
                        .IsUnique()
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("culinary_categories", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("average_rating");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("culinary_category_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("core_companies_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StructuredData")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_data");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("integer")
                        .HasColumnName("total_ratings");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<Guid>>("_tagIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("tag_ids");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("CompanyId", "AverageRating");

                    b.HasIndex("CompanyId", "CategoryId");

                    b.HasIndex("CompanyId", "Slug")
                        .IsUnique()
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("culinary_recipes", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.RecipeRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("core_companies_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("culinary_recipes_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("RecipeId");

                    b.HasIndex("CompanyId", "Status");

                    b.HasIndex("CompanyId", "RecipeId", "Status");

                    b.ToTable("culinary_recipe_ratings", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("core_companies_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("CompanyId", "Slug")
                        .IsUnique()
                        .HasFilter("\"deleted_at\" IS NULL");

                    b.HasIndex("CompanyId", "Status");

                    b.ToTable("culinary_tags", (string)null);
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Category", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.Culinary.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.CategorySeo", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CanonicalUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("canonical_url");

                            b1.Property<string>("MetaDescription")
                                .HasMaxLength(170)
                                .HasColumnType("character varying(170)")
                                .HasColumnName("meta_description");

                            b1.Property<string>("MetaTitle")
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("meta_title");

                            b1.HasKey("CategoryId");

                            b1.ToTable("culinary_categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("Parent");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Recipe", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.Culinary.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeAttributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Cuisine")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("cuisine");

                            b1.Property<int>("Difficulty")
                                .HasColumnType("integer")
                                .HasColumnName("difficulty");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FullDescription")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("full_description");

                            b1.Property<string>("Ingredients")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("ingredients");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.Property<string>("ShortDescription")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("short_description");

                            b1.Property<string>("Steps")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("steps");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeMedia", "Media", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("image_url");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeSeo", "Seo", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CanonicalUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("canonical_url");

                            b1.Property<string>("MetaDescription")
                                .IsRequired()
                                .HasMaxLength(170)
                                .HasColumnType("character varying(170)")
                                .HasColumnName("meta_description");

                            b1.Property<string>("MetaTitle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("meta_title");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeTiming", "Timing", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CookTime")
                                .HasColumnType("integer")
                                .HasColumnName("cook_time");

                            b1.Property<int>("PrepTime")
                                .HasColumnType("integer")
                                .HasColumnName("prep_time");

                            b1.Property<int>("RestTime")
                                .HasColumnType("integer")
                                .HasColumnName("rest_time");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeYield", "Yield", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("YieldTotal")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("yield_total");

                            b1.HasKey("RecipeId");

                            b1.ToTable("culinary_recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Media")
                        .IsRequired();

                    b.Navigation("Seo")
                        .IsRequired();

                    b.Navigation("Timing")
                        .IsRequired();

                    b.Navigation("Yield")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.RecipeRating", b =>
                {
                    b.HasOne("Nexora.Domain.Entities.Culinary.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nexora.Domain.ValueObjects.Culinary.RecipeScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("RecipeRatingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("score");

                            b1.HasKey("RecipeRatingId");

                            b1.ToTable("culinary_recipe_ratings");

                            b1.WithOwner()
                                .HasForeignKey("RecipeRatingId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexora.Domain.Entities.Culinary.Category", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
