services:
  nexora-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nexora-api

    network_mode: host

    volumes:
      - ./Nexora.Api/upload:/app/upload

    env_file:
      - ./Nexora.Api/.env.development

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:4000

    restart: unless-stopped
